# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Url Shortener' do
  pod 'Alamofire', '~> 3.0'
  pod 'JLToast', '~> 1.3'
end

target 'Url ShortenerTests' do

end

target 'Url ShortenerUITests' do

end

